# Generated by Django 6.0.1 on 2026-04-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='region',
            field=models.CharField(default='not_set', max_length=50),
            preserve_default=False,
        ),
    ]
