# Generated by Django 6.0.1 on 2026-05-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_report_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reporter_email',
            field=models.EmailField(default='unknown@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter_phone',
            field=models.CharField(default='00000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
