# Generated by Django 6.0.1 on 2026-05-24 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_report_reporter_email_report_reporter_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='reporter_name',
            new_name='reporter_region',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reporter_email',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reporter_phone',
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='source_type',
            field=models.CharField(default='SMS', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
