# Generated by Django 6.0.1 on 2026-06-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_reporter_name_report_reporter_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='phone_country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='region',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
